- src/main/java/com/project/perpetcare/domain/Pet.java
- src/main/resources/mapper/pet-service-mapping.xml
- src/test/java/com/project/perpetcare/PetTest.java
> feat: update test

- src/main/java/com/project/perpetcare/domain/User.java
- src/main/resources/mapper/auth-service-mapping.xml
- src/main/resources/mapper/profile-service-mapping.xml
- src/test/java/com/project/perpetcare/AuthTest.java
> feat:로그인 mapper,단위테스트

- src/main/java/com/project/perpetcare/domain/Opening.java
- src/main/java/com/project/perpetcare/domain/Rate.java
- src/main/resources/mapper/search-service-mapping.xml
- src/test/java/com/project/perpetcare/AuthTest.java
> chore: pull을 위한 commit

- src/main/java/com/project/perpetcare/controller/PetController.java
- src/main/java/com/project/perpetcare/domain/Rate.java
- src/main/resources/config/SqlMapConfig.xml
- src/main/resources/mapper/search-service-mapping.xml
- src/test/java/com/project/perpetcare/SearchTest.java
> feat: search by filter mapper and unit test

- src/main/webapp/components/footer.html
- src/main/webapp/css/home.css
- src/main/webapp/home.html
- src/main/webapp/login.jsp
> feat : footer 컴포넌트화

- src/main/webapp/search.jsp
> feat: search jsp layout 거의 완성

- src/main/java/com/project/perpetcare/controller/AuthController.java
- src/main/java/com/project/perpetcare/controller/ProfileController.java
- src/main/java/com/project/perpetcare/service/AuthService.java
- src/main/resources/mapper/auth-service-mapping.xml
- src/main/webapp/WEB-INF/views/profilePage/experiencePage.jsp
- src/main/webapp/css/home.css
- src/test/java/com/project/perpetcare/AuthTest.java
> feat: 로그인 안됨!!!

- src/main/java/com/project/perpetcare/controller/AuthController.java
- src/main/java/com/project/perpetcare/controller/ProfileController.java
> feat: controller 수정 

- src/main/java/com/project/perpetcare/controller/AuthController.java
- src/main/webapp/home.html
> feat: home에서 sign in get요청

- src/main/java/com/project/perpetcare/controller/ApplyController.java
- src/main/java/com/project/perpetcare/controller/OpeningController.java
- src/main/java/com/project/perpetcare/controller/PetController.java
- src/main/java/com/project/perpetcare/service/PetService.java
- src/main/webapp/WEB-INF/views/openingPage/opening-apply.jsp
- src/main/webapp/WEB-INF/views/openingPage/opening-create.jsp
- src/main/webapp/WEB-INF/views/openingPage/opening-success.jsp
- src/main/webapp/WEB-INF/views/openingPage/opening-view.jsp
> feat: pet image fix

- src/main/java/com/project/perpetcare/controller/SearchController.java
- src/main/java/com/project/perpetcare/dao/SearchDAO.java
- src/main/resources/mapper/search-service-mapping.xml
- src/main/webapp/search.jsp
> feat: search by filter ajax and controller 작성 중

- src/main/java/com/project/perpetcare/controller/SearchController.java
- src/main/webapp/search.jsp
> feat: search by location loading ajax 완료

- src/main/webapp/WEB-INF/views/openingPage/opening-view.jsp
- src/main/webapp/WEB-INF/views/profilePage/applyOpening.jsp
- src/main/webapp/WEB-INF/views/profilePage/experiencePage.jsp
- src/main/webapp/WEB-INF/views/profilePage/myOpening.jsp
- src/main/webapp/WEB-INF/views/profilePage/petPage2.jsp
- src/main/webapp/WEB-INF/views/profilePage/recentOpening.jsp
- src/main/webapp/components/header.jsp
- src/main/webapp/css/experiencePage.css
> feat: mypage 틀 완성

- src/main/java/com/project/perpetcare/controller/PetController.java
- src/main/webapp/WEB-INF/views/profilePage/petPage2.jsp
> feat : petPage 2

- src/main/java/com/project/perpetcare/controller/PetController.java
- src/main/java/com/project/perpetcare/controller/ProfileController.java
- src/main/java/com/project/perpetcare/dao/ProfileDAO.java
- src/main/java/com/project/perpetcare/domain/User.java
- src/main/java/com/project/perpetcare/service/ProfileService.java
- src/main/webapp/WEB-INF/views/profilePage/experiencePage.jsp
- src/main/webapp/WEB-INF/views/profilePage/petPage2.jsp
- src/main/webapp/css/experiencePage.css
- src/test/java/com/project/perpetcare/ProfileTest.java
> feat : pet & mypage & user

- src/main/java/com/project/perpetcare/dao/SearchDAO.java
- src/main/java/com/project/perpetcare/service/OpeningService.java
- src/main/java/com/project/perpetcare/service/SearchService.java
- src/main/resources/mapper/search-service-mapping.xml
- src/main/webapp/WEB-INF/views/openingPage/opening-create.jsp
- src/test/java/com/project/perpetcare/SearchTest.java
> feat: 공고 작성&조회 시 주소 입력 완료

- src/main/java/com/project/perpetcare/controller/ProfileController.java
- src/main/webapp/WEB-INF/views/profilePage/experiencePage.jsp
- src/main/webapp/WEB-INF/views/profilePage/myInfo.jsp
- src/main/webapp/components/footer.jsp
- src/main/webapp/components/gradeModal.jsp
- src/main/webapp/css/experiencePage.css
> feat: experience 오류 수정 및 footer.jsp 파일 생성 및 정보수정 jsp/css 완료

- src/main/java/com/project/perpetcare/controller/ProfileController.java
- src/main/webapp/WEB-INF/views/profilePage/petPage2.jsp
> feat : 다른 사람 프로필 마이페이지 불러오기 실패!!

- src/main/java/com/project/perpetcare/controller/ProfileController.java
- src/main/webapp/WEB-INF/views/profilePage/experiencePage.jsp
> feat: 마이페이지 - 경험 남이볼때

- src/main/java/com/project/perpetcare/controller/ProfileController.java
> feat:남의 프로필보기
